name: Continuous Integration and Continuous Delivery code - CI/CD flow

on: [push, pull_request] 
# push:
#   branches:["main", "every branch I want"]
jobs:
  job1:
    env:
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      DATABASE_NAME: fastAPI
      DATABASE_USERNAME: postgres
      SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3
     # - name: some simple test step
     #   run: echo "helo test echo" 
      - name: Install Python version 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Upgrading pip
        run: python -m pip install --upgrade pip
      - name: Install all dependencies
        run: pip install -r ruquirements.txt
      - name: Testing using pytest
        run: |
          pip install pytest
          pytest
       