name: Continuous Integration and Continuous Delivery code - CI/CD flow

on: [push, pull_request] 
# push:
#   branches:["main", "every branch I want"]
jobs:
  job1:
    envitonment: 
      name: Testing env
    env:
      DATABASE_HOSTNAME: ${{secrets.DATABASE_HOSTNAME}}
      DATABASE_PORT: ${{sectets.DATABASE_PORT}}
      DATABASE_NAME: ${{sectets.DATABASE_NAME}}
      DATABASE_USERNAME: ${{sectets.DATABASE_USERNAME}}
      SECRET_KEY: ${{sectets.SECRET_KEY}}
      ALGORITHM: ${{sectets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{sectets.ACCESS_TOKEN_EXPIRE_MINUTES}}
      DATABASE_PASSWORD: ${{sectets.DATABASE_PASSWORD}}
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3
     # - name: some simple test step
     #   run: echo "helo test echo" 
      - name: Install Python version 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Upgrading pip
        run: python -m pip install --upgrade pip
      - name: Install all dependencies
        run: pip install -r ruquirements.txt
      - name: Testing using pytest
        run: |
          pip install pytest
          pytest
       