"""auto-vote

Revision ID: 9f14df30c84d
Revises: 6e5f0c992693
Create Date: 2022-12-27 23:14:20.439825

"""
from alembic import op
import sqlalchemy as sa

# revision auto created by alembic based on models.py
# using command: alembic revision --autogenerate -m "auto-vote"

# revision identifiers, used by Alembic.
revision = '9f14df30c84d'
down_revision = '6e5f0c992693'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    # ### end Alembic commands ###
